// Auto-generated by generate-manifest.js — do not edit by hand.
// Run: node generate-manifest.js
window.PAPERS_DATA = [
  {
    "id": "ehr-biases-deficiencies",
    "title": "Biases in Electronic Health Records Data for Generating Real-World Evidence",
    "authors": [
      "Al-Sahab, B.",
      "Leviton, A.",
      "Loddenkemper, T.",
      "Paneth, N.",
      "Zhang, B."
    ],
    "year": 2024,
    "dataset_type": [
      "Healthcare"
    ],
    "link": "https://doi.org/10.1007/s41666-023-00153-2",
    "dataset_schema": [
      {
        "label": "Administrative and Billing Data",
        "description": "ICD codes, insurance type, billing records."
      },
      {
        "label": "Clinical and Medical Data",
        "description": "Lab tests (LOINC), SNOMED/CPT codes, vital signs, medications, free-text notes, radiology images."
      }
    ],
    "original_intent": [
      {
        "label": "Administrative",
        "description": "Reimbursement, healthcare management, legal documentation."
      },
      {
        "label": "Clinical",
        "description": "Patient care, medical history documentation, clinical decision-making."
      }
    ],
    "repurposed_use": "Combined as real-world data to generate clinical evidence for research, treatment evaluation, and decision support outside controlled trials.",
    "limitations": [
      {
        "label": "Selection Bias",
        "description": "Only includes individuals interacting with healthcare systems, excluding underserved populations."
      },
      {
        "label": "Documentation Bias",
        "description": "Data reflects billing incentives rather than research completeness."
      },
      {
        "label": "Information Bias",
        "description": "Incomplete histories and misclassification of diseases."
      },
      {
        "label": "Temporal Instability",
        "description": "Recorded timestamps may not reflect true clinical events."
      }
    ],
    "transformations": [
      {
        "label": "NLP Processing",
        "description": "Extract structured information from clinical notes."
      },
      {
        "label": "Feature Engineering",
        "description": "Phenotyping using rules or machine learning."
      },
      {
        "label": "Imputation",
        "description": "Fill missing data values."
      },
      {
        "label": "Data Integration",
        "description": "Link with social determinants datasets."
      }
    ],
    "notes": "Highlights representational bias where data reflects healthcare system processes rather than underlying clinical reality. :contentReference[oaicite:0]{index=0}"
  },
  {
    "id": "gps-mobility-epidemic-modeling",
    "title": "The Potential and Challenges of GPS Mobility Data for Epidemic Modeling",
    "authors": [
      "Barreras, F.",
      "Watts, D. J."
    ],
    "year": 2024,
    "dataset_type": [
      "Geospatial",
      "Demographic"
    ],
    "link": "https://doi.org/10.1038/s43588-024-00637-0",
    "dataset_schema": [
      {
        "label": "GPS Mobility Data",
        "description": "Latitude, longitude, timestamps, device ID, dwell time, inferred home location, visit frequency."
      },
      {
        "label": "Demographic Metadata",
        "description": "Census block group attributes (income, race, education)."
      }
    ],
    "original_intent": [
      {
        "label": "GPS Data",
        "description": "Advertising, retail analytics, and consumer behaviour tracking."
      },
      {
        "label": "Census Data",
        "description": "Population statistics and demographic tracking."
      }
    ],
    "repurposed_use": "Used for COVID-19 modelling, estimating transmission networks, evaluating lockdown policies, and urban mobility analysis.",
    "limitations": [
      {
        "label": "Selection Bias",
        "description": "Under-representation of low-income and low-smartphone populations."
      },
      {
        "label": "Granularity",
        "description": "Aggregation to census level removes within-area variation."
      },
      {
        "label": "Privacy and Ethical Risk",
        "description": "Re-identification risk despite anonymisation."
      }
    ],
    "transformations": [
      {
        "label": "Reweighting",
        "description": "Adjust sample to match population demographics."
      },
      {
        "label": "Validation",
        "description": "Compare against ground-truth mobility surveys."
      },
      {
        "label": "Feature Engineering",
        "description": "Infer home locations and visits."
      },
      {
        "label": "Privacy Preservation",
        "description": "Apply differential privacy techniques."
      }
    ],
    "notes": "Demonstrates how commercial data repurposing introduces structural inequities in public health modelling."
  },
  {
    "id": "diffusion-medical-innovation-stars",
    "title": "The Diffusion of a Medical Innovation: Is Success in the Stars?",
    "authors": [
      "Burke, M.A.",
      "Fournier, G.M.",
      "Prasad, K."
    ],
    "year": 2007,
    "dataset_type": [
      "Healthcare"
    ],
    "link": "https://doi.org/10.1287/mnsc.2015.2232",
    "dataset_schema": [
      {
        "label": "AHCA Hospital Discharge Dataset",
        "description": "Patient demographics (age, sex, zip), ICD diagnosis and procedure codes, DRG discharge codes, admission/discharge dates, hospital identifiers, attending physician and surgeon identifiers, payer type (Medicare, Medicaid, private, self-pay)."
      },
      {
        "label": "Physician Dataset (Star vs Non-Star)",
        "description": "Physician identity, education and training history, residency institutions, hospital prestige indicators, inferred physician status (star vs non-star)."
      }
    ],
    "original_intent": [
      {
        "label": "AHCA",
        "description": "Hospital billing, regulatory compliance, reimbursement tracking, and health services policy evaluation."
      },
      {
        "label": "Physician",
        "description": "Track physician qualifications, training backgrounds, and workforce characteristics to assess quality and experience."
      }
    ],
    "repurposed_use": "Datasets were linked across patients, physicians, hospitals, and time to analyse how medical innovations (coronary stents) diffuse, specifically examining whether high-status ('star') physicians influence adoption behaviour.",
    "limitations": [
      {
        "label": "Longitudinal (Time) Tracking",
        "description": "AHCA lacks stable patient identifiers, preventing tracking of patient outcomes over time."
      },
      {
        "label": "Accessibility",
        "description": "Data requires payment, limiting accessibility and reproducibility."
      },
      {
        "label": "Schema Incompleteness",
        "description": "Limited to attending physician and surgeon; excludes broader care team (e.g., nurses, multidisciplinary staff)."
      },
      {
        "label": "Construct Validity",
        "description": "'Star' status is inferred from training institutions rather than directly observed, introducing measurement bias."
      },
      {
        "label": "Omitted Variables",
        "description": "Missing factors such as hospital culture and selection effects may bias results."
      },
      {
        "label": "Privacy and Ethical Risk",
        "description": "Linking datasets and potential augmentation (e.g., with social or environmental data) raises consent and privacy concerns."
      }
    ],
    "transformations": [
      {
        "label": "Filtering",
        "description": "Select relevant patient records from AHCA dataset based on procedures and conditions."
      },
      {
        "label": "Data Integration",
        "description": "Merge patient, physician, and hospital datasets to create linked longitudinal structures."
      },
      {
        "label": "Feature Engineering",
        "description": "Construct 'star physician' variable based on residency at top-ranked hospitals."
      },
      {
        "label": "Discretisation",
        "description": "Convert continuous stent usage into binary adoption variable (≥3 uses defines adoption)."
      }
    ],
    "notes": "Demonstrates how administrative healthcare data can be repurposed for innovation diffusion research. Highlights the need for proxy variables when key constructs are unobserved and the importance of linking multi-level datasets (patient, physician, hospital)."
  },
  {
    "id": "medical-technology-abandonment",
    "title": "The When and Why of Abandonment: The Role of Organizational Differences in Medical Technology Life Cycles",
    "authors": [
      "Greenwood, B. N.",
      "Agarwal, R.",
      "Agarwal, R.",
      "Gopal, A."
    ],
    "year": 2017,
    "dataset_type": [
      "Healthcare"
    ],
    "link": "http://www.jstor.org/stable/45149123",
    "dataset_schema": [
      {
        "label": "AHCA Hospital Discharge Dataset",
        "description": "Patient demographics, ICD codes, DRG discharge codes, admission/discharge dates, hospital identifiers, physician identifiers, payer type."
      },
      {
        "label": "Hospital Organisational Dataset",
        "description": "Hospital identity, ownership classification (for-profit, non-profit, academic medical centre), location."
      }
    ],
    "original_intent": [
      {
        "label": "AHCA",
        "description": "Billing, compliance, reimbursement tracking, and policy evaluation."
      },
      {
        "label": "Hospital Organisational",
        "description": "Classify health systems and analyse institutional incentives and regulatory structures."
      }
    ],
    "repurposed_use": "Linked datasets to analyse how organisational incentives influence adoption and abandonment of medical technologies over time.",
    "limitations": [
      {
        "label": "Construct Validity",
        "description": "Hospital type used as proxy for incentives and culture, oversimplifying organisational differences."
      },
      {
        "label": "Temporal Instability",
        "description": "Hospital characteristics change over time but are treated as static classifications."
      },
      {
        "label": "Granularity",
        "description": "Mismatch between granular patient-level data and high-level hospital organisational data."
      }
    ],
    "transformations": [
      {
        "label": "Temporal Structuring",
        "description": "Convert cross-sectional data into longitudinal time series aligned with technology introduction periods."
      },
      {
        "label": "Data Integration",
        "description": "Link patient, hospital, and technology datasets."
      },
      {
        "label": "Feature Engineering",
        "description": "Derive adoption and abandonment variables from procedure codes."
      },
      {
        "label": "Aggregation",
        "description": "Aggregate patient-level data to hospital-level metrics (adoption rate, abandonment rate)."
      }
    ],
    "notes": "Illustrates reinterpretation of billing codes as behavioural signals of technology adoption and shift in unit of analysis from patient to organisation."
  },
  {
    "id": "understanding-and-improvin-data-repurposing",
    "title": "Understanding and Improving Data Repurposing",
    "authors": [
      "Parsons, J.",
      "Lukyanenko, R.",
      "Greenwood, B. N.",
      "Cooper, C. B."
    ],
    "year": 2026,
    "dataset_type": [
      "Geospatial",
      "Bird Watching"
    ],
    "link": "https://doi.org/10.25300/MISQ/2025/18361",
    "dataset_schema": [
      {
        "label": "Neighbourhood Nestwatch (citizen-generated reports of birds in backyards (citizen-generated reports of birds in backyards))",
        "description": "location data, observation metadata (species, count, date, location, observer), species data, breeding/nest data, effort metrics (duration, distance, area)."
      },
      {
        "label": "World atlas of artificial night sky brightness",
        "description": "Ratio to natural brightness, Artificial brightness (μcd/m²), Approximate total brightness (mcd/m²) of 1777m resolution, Anthropogenic noise data of expected sound pressures of 270m resolution"
      }
    ],
    "original_intent": [
      {
        "label": "Neighbourhood Nestwatch",
        "description": "Bird population monitoring, environmental engagement"
      },
      {
        "label": "World atlas",
        "description": "systematically quantify and map global light pollution levels to support scientific research and understand the environmental and societal impacts of artificial night sky brightness."
      }
    ],
    "repurposed_use": "Repurposed during COVID-19 lockdowns to study the effect of reduced human activity and light pollution on songbird physiological health by augmenting with geospatial light/noise datasets.",
    "limitations": [
      {
        "label": "Geographic Coverage",
        "description": "Uneven between datasets."
      },
      {
        "label": "Intra-data Inconsistenty",
        "description": "Data collected with inconsistent effort across participants."
      },
      {
        "label": "Granularity",
        "description": "Data could only match the coarsest resolution, leading to loss of potentially valuable information."
      }
    ],
    "transformations": [
      {
        "label": "Join",
        "description": "Geospatial light pollution maps, noise pollution layers, land cover datasets"
      },
      {
        "label": "Normalisation",
        "description": "Detection efforts"
      }
    ],
    "notes": "Introduces the concept of data 'elasticity': the degree to which data can be stretched to fit new schemas. Distinguishes repurposing (schema change required) from reuse (existing schema sufficient). Identifies actors, enablers, and constraints shaping the repurposing ecosystem."
  }
];
