// Auto-generated by generate-manifest.js — do not edit by hand.
// Run: node generate-manifest.js
window.PAPERS_DATA = [
  {
    "id": "diffusion-medical-innovation-stars",
    "title": "The Diffusion of a Medical Innovation: Is Success in the Stars?",
    "authors": [
      "Burke, M.A.",
      "Fournier, G.M.",
      "Prasad, K."
    ],
    "year": 2007,
    "dataset_type": [
      "Healthcare"
    ],
    "link": "https://doi.org/10.1287/mnsc.2015.2232",
    "dataset_schema": [
      {
        "label": "AHCA Hospital Discharge Dataset",
        "description": "Patient demographics (age, sex, zip), ICD diagnosis and procedure codes, DRG discharge codes, admission/discharge dates, hospital identifiers, attending physician and surgeon identifiers, payer type (Medicare, Medicaid, private, self-pay)."
      },
      {
        "label": "Physician Dataset (Star vs Non-Star)",
        "description": "Physician identity, education and training history, residency institutions, hospital prestige indicators, inferred physician status (star vs non-star)."
      }
    ],
    "original_intent": [
      {
        "label": "AHCA",
        "description": "Hospital billing, regulatory compliance, reimbursement tracking, and health services policy evaluation."
      },
      {
        "label": "Physician",
        "description": "Track physician qualifications, training backgrounds, and workforce characteristics to assess quality and experience."
      }
    ],
    "repurposed_use": "Datasets were linked across patients, physicians, hospitals, and time to analyse how medical innovations (coronary stents) diffuse, specifically examining whether high-status ('star') physicians influence adoption behaviour.",
    "limitations": [
      {
        "label": "Longitudinal (Time) Tracking",
        "description": "AHCA lacks stable patient identifiers, preventing tracking of patient outcomes over time."
      },
      {
        "label": "Accessibility",
        "description": "Data requires payment, limiting accessibility and reproducibility."
      },
      {
        "label": "Schema Incompleteness",
        "description": "Limited to attending physician and surgeon; excludes broader care team (e.g., nurses, multidisciplinary staff)."
      },
      {
        "label": "Construct Validity",
        "description": "'Star' status is inferred from training institutions rather than directly observed, introducing measurement bias."
      },
      {
        "label": "Omitted Variables",
        "description": "Missing factors such as hospital culture and selection effects may bias results."
      },
      {
        "label": "Privacy and Ethical Risk",
        "description": "Linking datasets and potential augmentation (e.g., with social or environmental data) raises consent and privacy concerns."
      }
    ],
    "transformations": [
      {
        "label": "Filtering",
        "description": "Select relevant patient records from AHCA dataset based on procedures and conditions."
      },
      {
        "label": "Data Integration",
        "description": "Merge patient, physician, and hospital datasets to create linked longitudinal structures."
      },
      {
        "label": "Feature Engineering",
        "description": "Construct 'star physician' variable based on residency at top-ranked hospitals."
      },
      {
        "label": "Discretisation",
        "description": "Convert continuous stent usage into binary adoption variable (≥3 uses defines adoption)."
      }
    ],
    "notes": "Demonstrates how administrative healthcare data can be repurposed for innovation diffusion research. Highlights the need for proxy variables when key constructs are unobserved and the importance of linking multi-level datasets (patient, physician, hospital)."
  },
  {
    "id": "understanding-and-improvin-data-repurposing",
    "title": "Understanding and Improving Data Repurposing",
    "authors": [
      "Parsons, J.",
      "Lukyanenko, R.",
      "Greenwood, B. N.",
      "Cooper, C. B."
    ],
    "year": 2026,
    "dataset_type": [
      "Geospatial Data",
      "Bird Watching"
    ],
    "link": "https://doi.org/10.25300/MISQ/2025/18361",
    "dataset_schema": [
      {
        "label": "Neighbourhood Nestwatch (citizen-generated reports of birds in backyards (citizen-generated reports of birds in backyards))",
        "description": "location data, observation metadata (species, count, date, location, observer), species data, breeding/nest data, effort metrics (duration, distance, area)."
      },
      {
        "label": "World atlas of artificial night sky brightness",
        "description": "Ratio to natural brightness, Artificial brightness (μcd/m²), Approximate total brightness (mcd/m²) of 1777m resolution, Anthropogenic noise data of expected sound pressures of 270m resolution"
      }
    ],
    "original_intent": [
      {
        "label": "Neighbourhood Nestwatch",
        "description": "Bird population monitoring, environmental engagement"
      },
      {
        "label": "World atlas",
        "description": "systematically quantify and map global light pollution levels to support scientific research and understand the environmental and societal impacts of artificial night sky brightness."
      }
    ],
    "repurposed_use": "Repurposed during COVID-19 lockdowns to study the effect of reduced human activity and light pollution on songbird physiological health by augmenting with geospatial light/noise datasets.",
    "limitations": [
      {
        "label": "Geographic Coverage",
        "description": "Uneven between datasets."
      },
      {
        "label": "Intra-data Inconsistenty",
        "description": "Data collected with inconsistent effort across participants."
      },
      {
        "label": "Granularity",
        "description": "Data could only match the coarsest resolution, leading to loss of potentially valuable information."
      }
    ],
    "transformations": [
      {
        "label": "Join",
        "description": "Geospatial light pollution maps, noise pollution layers, land cover datasets"
      },
      {
        "label": "Normalisation",
        "description": "Detection efforts"
      }
    ],
    "notes": "Introduces the concept of data 'elasticity': the degree to which data can be stretched to fit new schemas. Distinguishes repurposing (schema change required) from reuse (existing schema sufficient). Identifies actors, enablers, and constraints shaping the repurposing ecosystem."
  }
];
